# Generated by Django 5.2.6 on 2025-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_tag_page_post_comment_richtextcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtextcontent',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
