# Generated by Django 5.2.6 on 2025-09-26 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_account_owner_contact_owner"),
    ]

    operations = []
