# Generated by Django 5.2.6 on 2025-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bulkoperation_globalsearchindex_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost')], default='in_progress', max_length=20),
        ),
    ]
