# Generated by Django 5.2.6 on 2025-09-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_account_industry_account_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='name',
            new_name='title',
        ),
    ]
