# Generated by Django 5.2.6 on 2025-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_name_deal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20),
        ),
    ]
