# Generated by Django 5.2.6 on 2025-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_populate_task_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
