# Generated by Django 5.2.6 on 2025-09-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_account_tags_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(),
        ),
    ]
