# Generated by Django 5.2.6 on 2025-09-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_account_tags_contact_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='TaskTemplate',
            new_name='ProjectTemplate',
        ),
        migrations.RenameModel(
            old_name='TaskType',
            new_name='ProjectType',
        ),
    ]
