# Generated by Django 5.2.6 on 2025-09-30 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_add_inventory_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_deals", models.PositiveIntegerField(default=0)),
                ("won_deals", models.PositiveIntegerField(default=0)),
                ("lost_deals", models.PositiveIntegerField(default=0)),
                ("active_projects", models.PositiveIntegerField(default=0)),
                ("completed_projects", models.PositiveIntegerField(default=0)),
                ("total_contacts", models.PositiveIntegerField(default=0)),
                ("total_accounts", models.PositiveIntegerField(default=0)),
                (
                    "inventory_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outstanding_invoices",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "overdue_invoices",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLifetimeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_deals", models.PositiveIntegerField(default=0)),
                (
                    "average_deal_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deal_win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("customer_since", models.DateField()),
                ("last_activity", models.DateField()),
                (
                    "predicted_clv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "clv_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("segments", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clv",
                        to="main.contact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_outcome",
                    models.CharField(
                        choices=[
                            ("won", "Will Win"),
                            ("lost", "Will Lose"),
                            ("pending", "Still Pending"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("predicted_close_date", models.DateField(blank=True, null=True)),
                ("factors", models.JSONField(default=dict)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="main.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevenueForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "forecast_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "predicted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_interval_lower",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_interval_upper",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "forecast_method",
                    models.CharField(
                        choices=[
                            ("linear_regression", "Linear Regression"),
                            ("moving_average", "Moving Average"),
                            ("seasonal_arima", "Seasonal ARIMA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("factors", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-forecast_date"],
                "unique_together": {
                    ("forecast_date", "forecast_period", "forecast_method")
                },
            },
        ),
    ]
