# Generated by Django 5.2.6 on 2025-10-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_certification_technician_enhanceduser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="industry",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="website",
            field=models.URLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="deal",
            name="close_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                db_index=True,
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="value",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
