# Generated by Django 5.2.7 on 2025-10-07 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_add_phone_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="status",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="title",
        ),
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(blank=True, default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="main.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="deal",
            name="close_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.contact",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="probability",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("qualified", "Qualified"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="lead",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
