# Generated by Django 5.2.7 on 2025-10-09 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0039_alter_activitylog_user_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='recurrence_end_date',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(db_index=True, default=22, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='document_hash',
            field=models.CharField(blank=True, help_text='Hash of canonicalized document content for tamper detection', max_length=128),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Result of integrity verification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.account'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='close_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='main.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='main.dealstage'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='technician',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
