# Generated by Django 5.2.6 on 2025-10-16 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0044_monthlydistribution_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetv2",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="close_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deals",
                to="main.dealstage",
            ),
        ),
        migrations.AlterField(
            model_name="digitalsignature",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="digitalsignature",
            name="document_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="digitalsignature",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalsignature",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="digitalsignature",
            name="signer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="monthlydistribution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("part", "Part"),
                    ("equipment", "Equipment"),
                    ("consumable", "Consumable"),
                    ("finished_good", "Finished Good"),
                ],
                default="part",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="main.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="CoverageShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[("polygon", "Polygon"), ("circle", "Circle")],
                        max_length=20,
                    ),
                ),
                ("geometry", models.JSONField(default=dict)),
                ("color", models.CharField(default="#3b82f6", max_length=16)),
                ("priority_level", models.PositiveSmallIntegerField(default=1)),
                ("properties", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_shapes",
                        to="main.technician",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
