name: i18n Sync

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  i18n-sync:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Extract translation keys
        run: npm run i18n:extract

      - name: Validate translations
        run: npm run i18n:validate

      - name: Lint (optional)
        run: npm run lint
