name: Spec Compile

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  spec-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile Specs
        run: |
          python tools/spec_compile.py --src spec --out spec/COMPILED_SPEC.md

      - name: Upload Compiled Spec
        uses: actions/upload-artifact@v4
        with:
          name: compiled-spec
          path: spec/COMPILED_SPEC.md
          if-no-files-found: error
